### ISSUE TITLE
Problems installing healpy with python 2.7 at CentOS

### ISSUE THREAD

**Issue by danimolinamartinez** [healpy/healpy#110]
Hi,

I've installed healpix libraries at my system.
I've installed python 2.7 (CentOS uses python 2.6).
And I've installed many libraries (matplotlib, asciitable, chealpy, Cython, multiprocessing, nose, numpy, pyfits, scipy,...) at python, using pip or easy_install.
But unfortunately those utilities include healpy version 0.10.2, very far from the current one (1.6.2), and:
If I try to upgrade/update healpy using these utilities, I get a long traceback.
If I try to install healpy downloading the .tgz and using python-2.7 setup.py install, I get a long traceback.
Which other way can I use?

Thank you so much,

**Comment by prodev-paris** [comment]
Same error here (using command: `python setup.py install --user`):
`healpy-1.8.6/healpixsubmodule/src/cxx/autotools/libsharp/sharp_core_inc2.c:225: internal compiler error: in extract_component, at tree-complex.c:594`

I don't know if it matter but I build against external Healpix and cfitsio ([as documented on official site](https://healpy.readthedocs.org/en/latest/install.html))

My env:
healpy-1.8.6 (from https://pypi.python.org/pypi/healpy)
gcc (SUSE Linux) 4.3.4
Python 2.6.9

**Comment by lpsinger** [comment]
@prodev-paris, Healpy is building its own HEALPix library here, as one can tell from the path in your error message (`healpy-1.8.6/healpixsubmodule/src/cxx/autotools/libsharp/sharp_core_inc2.c`). Would you please post your full build log?

**Comment by prodev-paris** [comment]
You are totally right! I realize that the error appear since I forgot to set the env variable `PKG_CONFIG_PATH`
As stated in the log... :
```
[...]
running build_clib
checking if library 'cfitsio' is installed
Package cfitsio was not found in the pkg-config search path.
Perhaps you should add the directory containing `cfitsio.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cfitsio' found
building library 'cfitsio' from source
[...]
```

Thanks for your help!

But wait, anyway the compilation of this sub module (hte healpix module include in healpy sources) should have success anyway doesn't it?

**Comment by jamestsayre** [comment]
I'm running into the same error mentioned by others, in trying to compile healpy1.8.6 from anaconda2.1.0.  I've googled around on the subject and found some older posts suggesting it was errors in the healpix healpy is trying build, but it's not clear to me what the current resolution is.

Note, this is on an HPC machine, and I got the same error before and after I pointed to an existing install of cfitsio (i.e. the problem is with the healpix build as far as I can tell).

Note: I tried before and after loading cfitsio, got the same result, but posted the build log for the case where I had it loaded since there is less output.  I assume since the end result error is the same that the additional processing for building/using existing cfitsio doesn't matter.

~/healpy-1.8.6>python setup.py install healpy --user &> log.txt
```
running install
running bdist_egg
running egg_info
writing requirements to healpy.egg-info/requires.txt
writing healpy.egg-info/PKG-INFO
writing top-level names to healpy.egg-info/top_level.txt
writing dependency_links to healpy.egg-info/dependency_links.txt
checking if configure script for library 'cfitsio' exists
checking if configure script for library 'healpix_cxx' exists
reading manifest file 'healpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'healpy/test/data/ipython*'
warning: no previously-included files found matching 'cfitsio/*pdf'
warning: no previously-included files found matching 'cfitsio/*ps'
warning: no previously-included files found matching 'cfitsio/*doc'
warning: no previously-included files found matching 'cfitsio/*tex'
no previously-included directories found matching 'cfitsio/docs'
warning: no previously-included files found matching '*.so'
warning: no previously-included files found matching '*.a'
writing manifest file 'healpy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running build_clib
checking if library 'cfitsio' is installed
found 'cfitsio' installed, using it
checking if library 'healpix_cxx' is installed
Package healpix_cxx was not found in the pkg-config search path.
Perhaps you should add the directory containing `healpix_cxx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'healpix_cxx' found
building library 'healpix_cxx' from source
/bin/sh ./healpy-1.8.6/healpixsubmodule/src/cxx/autotools/configure --prefix=./healpy-1.8.6/build/temp.linux-x86_64-2.7 --disable-shared --with-pic --disable-maintainer-mode
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc -pthread
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -pthread accepts -g... yes
checking for gcc -pthread option to accept ISO C89... none needed
checking whether gcc -pthread understands -c and -o together... yes
checking dependency style of gcc -pthread... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc -pthread... /usr/x86_64-suse-linux/bin/ld
checking if the linker (/usr/x86_64-suse-linux/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 3458764513820540925
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-suse-linux/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -pthread object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -pthread -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -pthread supports -fno-rtti -fno-exceptions... no
checking for gcc -pthread option to produce PIC... -fPIC -DPIC
checking if gcc -pthread PIC flag -fPIC -DPIC works... yes
checking if gcc -pthread static flag -static works... yes
checking if gcc -pthread supports -c -o file.o... yes
checking if gcc -pthread supports -c -o file.o... (cached) yes
checking whether the gcc -pthread linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
checking for gcc -pthread option to accept ISO C99... -std=gnu99
checking for gcc -pthread -std=gnu99 option to support OpenMP... -fopenmp
checking whether C compiler accepts -fno-tree-vectorize... yes
checking whether C compiler accepts -fno-math-errno... yes
checking whether C compiler accepts -funsafe-math-optimizations... yes
checking whether C compiler accepts -fno-trapping-math... yes
checking whether C compiler accepts -fno-rounding-math... yes
checking whether C compiler accepts -fno-signaling-nans... yes
checking whether C compiler accepts -fcx-limited-range... yes
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -pthread accepts -g... yes
checking dependency style of g++ -pthread... gcc3
checking how to run the C++ preprocessor... g++ -pthread -E
checking for ld used by g++ -pthread... /usr/x86_64-suse-linux/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ -pthread linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ -pthread option to produce PIC... -fPIC -DPIC
checking if g++ -pthread PIC flag -fPIC -DPIC works... yes
checking if g++ -pthread static flag -static works... yes
checking if g++ -pthread supports -c -o file.o... yes
checking if g++ -pthread supports -c -o file.o... (cached) yes
checking whether the g++ -pthread linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for g++ -pthread option to support OpenMP... none needed
checking whether C++ compiler accepts -fno-tree-vectorize... yes
checking whether C++ compiler accepts -fno-math-errno... yes
checking whether C++ compiler accepts -funsafe-math-optimizations... yes
checking whether C++ compiler accepts -fno-trapping-math... yes
checking whether C++ compiler accepts -fno-rounding-math... yes
checking whether C++ compiler accepts -fno-signaling-nans... yes
checking whether C++ compiler accepts -fcx-limited-range... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CFITSIO... yes
checking for ffgnrwll in -lcfitsio... yes
checking fitsio.h usability... yes
checking fitsio.h presence... no
configure: WARNING: fitsio.h: accepted by the compiler, rejected by the preprocessor!
configure: WARNING: fitsio.h: proceeding with the compiler's result
checking for fitsio.h... yes
checking our pkgconfig libname... healpix_cxx
checking our pkgconfig version... 3.11.3
checking our pkgconfig_libdir... ${libdir}/pkgconfig
expanded our pkgconfig_libdir... ./healpy-1.8.6/build/temp.linux-x86_64-2.7/lib/pkgconfig
checking our pkgconfig_libfile... healpix_cxx.pc
checking our package / suffix... healpix_cxx / 
checking our pkgconfig description... healpix_cxx Library
checking our pkgconfig requires... 
checking our pkgconfig ext libs... -lhealpix_cxx
checking our pkgconfig cppflags... -fopenmp -I./healpy-1.8.6/build/temp.linux-x86_64-2.7/include
checking our pkgconfig ldflags... 
noninstalled pkgconfig -L ./healpy-1.8.6/build/temp.linux-x86_64-2.7/healpix_cxx/.libs
noninstalled pkgconfig -I /./healpy-1.8.6/healpixsubmodule/src/cxx/autotools
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing healpix_cxx.pc commands
config.status: creating healpix_cxx.pc.in
config.status: creating healpix_cxx.pc
config.status: creating healpix_cxx-uninstalled.pc
config.status: creating healpix_cxx-uninstalled.sh
make install
  CC       libsharp/sharp_core.lo
./healpy-1.8.6/healpixsubmodule/src/cxx/autotools/libsharp/sharp_core_inc2.c: In function 'inner_loop_5_1':
./healpy-1.8.6/healpixsubmodule/src/cxx/autotools/libsharp/sharp_core_inc2.c:627: internal compiler error: in extract_component, at tree-complex.c:594
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugs.opensuse.org/> for instructions.
make: *** [libsharp/sharp_core.lo] Error 1
Traceback (most recent call last):
  File "setup.py", line 452, in <module>
    license='GPLv2'
  File "./anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "./anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "./anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 109, in do_egg_install
  File "./anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "./anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 159, in run
  File "./anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "./anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "./anaconda/lib/python2.7/distutils/command/build_clib.py", line 116, in run
    self.build_libraries(self.libraries)
  File "setup.py", line 303, in build_libraries
    for key, value in self.build_library(lib_name, **build_info).items():
  File "setup.py", line 241, in build_library
    check_call(cmd, cwd=build_temp, env=self._environ)
  File "./anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'install']' returned non-zero exit status 2
```

**Comment by lpsinger** [comment]
@jamestsayre, would you please set the environment variable `V=1`, rebuild, and post the output? That should make it so that the full compiler commands are shown (rather than the abbreviated `  CC       libsharp/sharp_core.lo` format above). The build is supposed to be including certain flags to work around a similar-looking bug in GCC.

**Comment by jamestsayre** [comment]
Updated with the requested output, thanks.

**Comment by lpsinger** [comment]
OK, can you try setting the environment variables `CFLAGS=-fno-tree-fre` and `CXXFLAGS=-fno-tree-fre` and rebuilding?

**Comment by jamestsayre** [comment]
Ah, that worked.  It compiled and I can import healpy, though I do get the following warnings:

```In [1]: import healpy as hp
healpy/pixelfunc.py:103: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
healpy/sphtfunc.py:34: UserWarning: Warning: cannot import _healpy_pixel_lib module
  warnings.warn('Warning: cannot import _healpy_pixel_lib module')
healpy/sphtfunc.py:38: UserWarning: Warning: cannot import _healpy_fitsio_lib module
  warnings.warn('Warning: cannot import _healpy_fitsio_lib module')
healpy/sphtfunc.py:42: UserWarning: Warning: cannot import _sphtools module
  warnings.warn('Warning: cannot import _sphtools module')
healpy/__init__.py:57: UserWarning: Warning: cannot import query disc module
  warnings.warn('Warning: cannot import query disc module')
healpy/__init__.py:61: UserWarning: Warning: cannot import pixelfunc module
  warnings.warn('Warning: cannot import pixelfunc module')
healpy/__init__.py:68: UserWarning: Warning: cannot import _sphtools module
  warnings.warn('Warning: cannot import _sphtools module')
healpy/__init__.py:76: UserWarning: Warning: cannot import pixel lib module
  warnings.warn('Warning: cannot import pixel lib module')
```
I recognize the flags you suggested from an older fix I found involving changes to a config file that wasn't present (at least in the same place) in the current version's install files.  It didn't occur to me to try just setting them as environment variables.  Thanks!

**Comment by lpsinger** [comment]
@zonca, I thought that we had worked out that this compiler bug was specific to GCC 4.4. Do we also need to apply the workaround to 4.3?

**Comment by lpsinger** [comment]
@jamestsayre, you may get those error messages if you try to import healpy while within the source directory. Try changing to your home directory or elsewhere before importing healpy.
