### ISSUE TITLE
Empty cfitsio

### ISSUE THREAD

**Issue by salomanders** [healpy/healpy#215]
When I clone the repository I get an empty cfitsio directory which I think is the reason this error is being thrown (although possibly something else?):

checking if configure script for library 'cfitsio' exists
running 'autoreconf -i' for library 'cfitsio'
autoreconf: `configure.ac' or `configure.in' is required
Traceback (most recent call last):
  File "setup.py", line 444, in <module>
    license='GPLv2'
  File "/u/landers7/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/u/landers7/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/u/landers7/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/u/landers7/anaconda/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/u/landers7/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/u/landers7/anaconda/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/u/landers7/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 183, in finalize_options
    check_call(['autoreconf', '-i'], cwd=build_info['local_source'])
  File "/u/landers7/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['autoreconf', '-i']' returned non-zero exit status 1

**Comment by lpsinger** [comment]
@salomanders, did the development instructions work for you? You probably had not run `git submodule init` and `git submodule update`.
