### ISSUE TITLE
installation problem with healpy

### ISSUE THREAD

**Issue by sazabi4** [healpy/healpy#256]
I try to install healpy with pip and this is the error message I got

.....
.....
    checking for pkg-config... /opt/local/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for CFITSIO... yes
    checking for ffgnrwll in -lcfitsio... no
    configure: error: could not find the cfitsio library
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-PJav1b/healpy/setup.py", line 452, in <module>
        license='GPLv2'
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Python/2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_clib.py", line 116, in run
        self.build_libraries(self.libraries)
      File "/private/tmp/pip-build-PJav1b/healpy/setup.py", line 303, in build_libraries
        for key, value in self.build_library(lib_name, **build_info).items():
      File "/private/tmp/pip-build-PJav1b/healpy/setup.py", line 236, in build_library
        CC=cc, CXX=cxx, CFLAGS=cflags, CXXFLAGS=cxxflags))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 511, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/bin/sh', '/private/tmp/pip-build-PJav1b/healpy/healpixsubmodule/src/cxx/autotools/configure', '--prefix=/private/tmp/pip-build-PJav1b/healpy/build/temp.macosx-10.8-intel-2.7', '--disable-shared', '--with-pic', '--disable-maintainer-mode']' returned non-zero exit status 1

    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-PJav1b/healpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YlUAPU-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-PJav1b/healpy

I downloaded the installation file and run python setup.py install --user and I got the same error. Can anyone tell me what I should do to solve the problem?

**Comment by zonca** [comment]
sorry I have no experience with MACs, I would recommend you install Anaconda Python and install healpy there.

**Comment by lpsinger** [comment]
Hi @sazabi4! You seem to have MacPorts on your Mac, as I can tell from this line:

    checking for pkg-config... /opt/local/bin/pkg-config

Have you tried just installing Healpy with MacPorts, like this?

    sudo port install py27-healpy

**Comment by zonca** [comment]
not updated in more than a month.
