### ISSUE TITLE
healpy crashes when use anaconda python

### ISSUE THREAD

**Issue by vvinuv** [healpy/healpy#308]
Hello All
I was trying to install healpy with python from Anaconda2-2.4.0-Linux-x86_64. However, healpy  crashes without even installing it. Please see the below messages after healpy crashes. Do you have some work around this?
Thanks
Vinu

```
   config.status: creating healpix_cxx-uninstalled.pc
    config.status: creating healpix_cxx-uninstalled.sh
    make install
      CC     libsharp/sharp_core.lo
    /scratch/scratchdirs/vvinuv/pip-build-6k0X1W/healpy/healpixsubmodule/src/cxx/autotools/libsharp/sharp_core_inc2.c: In function 'calc_map2alm_4':
    /scratch/scratchdirs/vvinuv/pip-build-6k0X1W/healpy/healpixsubmodule/src/cxx/autotools/libsharp/sharp_core_inc2.c:225: internal compiler error: in extract_component, at tree-complex.c:594
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://bugs.opensuse.org/> for instructions.
    make: *** [libsharp/sharp_core.lo] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/scratch/scratchdirs/vvinuv/pip-build-6k0X1W/healpy/setup.py", line 465, in <module>
        license='GPLv2'
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/site-packages/setuptools-18.4-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/distutils/command/build_clib.py", line 116, in run
        self.build_libraries(self.libraries)
      File "/scratch/scratchdirs/vvinuv/pip-build-6k0X1W/healpy/setup.py", line 316, in build_libraries
        for key, value in self.build_library(lib_name, **build_info).items():
      File "/scratch/scratchdirs/vvinuv/pip-build-6k0X1W/healpy/setup.py", line 254, in build_library
        check_call(cmd, cwd=build_temp, env=self._environ)
      File "/global/project/projectdirs/des/vinu/software/anaconda2/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'install']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/global/project/projectdirs/des/vinu/software/anaconda2/bin/python -c "import setuptools, tokenize;__file__='/scratch/scratchdirs/vvinuv/pip-build-6k0X1W/healpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /scratch/scratchdirs/vvinuv/pip-XNpWCR-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /scratch/scratchdirs/vvinuv/pip-build-6k0X1W/healpy
```

**Comment by lpsinger** [comment]
What version of gcc are you using? Can you provide the output of `gcc --version`?

**Comment by vvinuv** [comment]
Thanks! It is GCC 4.4.7

**Comment by zonca** [comment]
You can try do conda install gcc and try to build with that gcc instead of
the system one.

**Comment by vvinuv** [comment]
Thanks all! I have found some work around. If you download the healpix from the sourceforge, then the steps are as following 
1. You need to edit Healpy_config() function in hpxconfig_functions.sh. Just edit python_version to "2.7" in that function. I am not quite sure why python_version=`${CAT} ${tmpfile} | ${AWK} '{print \$NF}'` doesn't work in that function
2. ./configure : It will show some languages you could use. I give 5 which is to compile healpy 
3. make healpy-all
4. make healpy-test

Thanks again!
