### ISSUE TITLE
Installation issue on 10.9.5

### ISSUE THREAD

**Issue by keflavich** [healpy/healpy#327]
I'm running into the following issue when trying to install healpy on mac 10.9.5:

```
...
checking whether C++ compiler accepts -fcx-limited-range... yes
/Users/adam/repos/healpy/healpixsubmodule/src/cxx/autotools/configure: line 16395: syntax error near unexpected token `CFITSIO,'
/Users/adam/repos/healpy/healpixsubmodule/src/cxx/autotools/configure: line 16395: `PKG_CHECK_MODULES(CFITSIO, cfitsio, , CFITSIO_LIBS=-lcfitsio)'
Traceback (most recent call last):
  File "setup.py", line 260, in build_library
    build_args = self.pkgconfig(pkg_config_name)
  File "setup.py", line 238, in pkgconfig
    args = [token[index:].decode() for token in check_output(cmd, env=env).split()]
  File "setup.py", line 78, in check_output
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('pkg-config', '--cflags-only-I', 'healpix_cxx >= 3.30.0')' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 511, in <module>
    license='GPLv2'
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/setuptools/command/install.py", line 67, in run
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/setuptools/command/install.py", line 109, in do_egg_install
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/site-packages/setuptools-19.6.2-py3.5.egg/setuptools/command/bdist_egg.py", line 160, in run
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/distutils/command/build_clib.py", line 115, in run
    self.build_libraries(self.libraries)
  File "setup.py", line 377, in build_libraries
    for key, value in self.build_library(lib_name, **build_info).items():
  File "setup.py", line 310, in build_library
    CC=cc, CXX=cxx, CFLAGS=cflags, CXXFLAGS=cxxflags))
  File "/Users/adam/anaconda/envs/astropy35/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '/Users/adam/repos/healpy/healpixsubmodule/src/cxx/autotools/configure', '--prefix=/Users/adam/repos/healpy/build/temp.macosx-10.5-x86_64-3.5', '--disable-shared', '--with-pic', '--disable-maintainer-mode']' returned non-zero exit status 2
```

Could you offer any suggestions on what might be causing this?  I'm trying to install from source on tag 1.9.1

**Comment by lpsinger** [comment]
When you build from git, you need to have a full installation of autotools because setup.py needs to bootstrap the healpix_cxx configure script and make files.

**Comment by keflavich** [comment]
@lpsinger thanks.  It looks like I have at least parts of autotools installed:
```
cyg ~/repos/healpy tags/1.9.1^0$ which pkg-config
/opt/local/bin//pkg-config
cyg ~/repos/healpy tags/1.9.1^0$ pkg-config --version
0.28
```

but maybe healpix still isn't getting installed?

```
cyg ~/repos/healpy tags/1.9.1^0$ pkg-config --cflags-only-I healpix_cxx>=3.30.0
Package healpix_cxx was not found in the pkg-config search path.
Perhaps you should add the directory containing `healpix_cxx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'healpix_cxx' found
```

Do I need to install the healpix submodule independently before running `python setup.py install`?  The [instructions on the readme](https://github.com/healpy/healpy/blob/master/README.rst#optional) say "no", but perhaps there is a step I've missed?

**Comment by keskitalo** [comment]
I've had the same problem. It seems to be caused by an incomplete installation of pkg-config. If you grab a copy of pkg.m4 and save it under healpixsubmodule/src/cxx/autotools/m4 it should solve the problem. You just need to regenerate the configure script with autoreconf.
