### ISSUE TITLE
1.12.2 doesn't install on Python 3.6 with pip

### ISSUE THREAD

**Issue by athornton** [healpy/healpy#462]
On both the SCL 3.6 on Linux and Brew 3.6.5 on MacOS I get a UnicodeDecodeError (same in both cases):

```
(hp) adam@ixitxachitl:~$ pip install healpy
Collecting healpy
  Downloading https://files.pythonhosted.org/packages/41/30/243b93018caf8c74cd674c44a521806908b91228dcae9d44e41662917d9a/healpy-1.12.2.tar.gz (4.1MB)
    100% |################################| 4.2MB 6.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/yb/jw5ph7ms481gw78_024tdgy00000gn/T/pip-install-ngvwsl15/healpy/setup.py", line 435, in <module>
        long_description=readme(),
      File "/private/var/folders/yb/jw5ph7ms481gw78_024tdgy00000gn/T/pip-install-ngvwsl15/healpy/setup.py", line 428, in readme
        return f.read()
      File "/Users/adam/Documents/src/Venvs/hp/bin/../lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5711: ordinal not in range(128)

    ----------------------------------------
```

**Comment by zonca** [comment]
ok, can you please try with 1.12.3 and report back?

**Comment by athornton** [comment]
The pip install succeeds again with 1.12.3.  Thanks!

**Comment by zonca** [comment]
thanks
