### ISSUE TITLE
Compilation Error on MacOS X 10.14.4

### ISSUE THREAD

**Issue by dendisuhubdy** [healpy/healpy#542]
I did a build on libtorrent then I wanted to install the python libtorrent bindings by executing
```
CC=cc CXX=c++ python3 setup.py install
```

Everything worked fine until I tried doing `import libtorrent`, I got this error message

```
 grokmachine@Dendis-MacBook-Pro   ~/dev/distributed/libtorrent     RC_1_2  cd ~                             ✔  8704  08:07:33 
 grokmachine@Dendis-MacBook-Pro   ~  python3                                                                   ✔  8705  08:07:35 
Python 3.7.2 (default, Feb 12 2019, 08:15:36)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_libtorrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'python_libtorrent'
>>> import libtorrent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/libtorrent.cpython-37m-darwin.so, 2): Symbol not found: _kSCCompAnyRegex
  Referenced from: /usr/local/lib/libtorrent-rasterbar.10.dylib
  Expected in: flat namespace
 in /usr/local/lib/libtorrent-rasterbar.10.dylib
>>> exit(

```

I assumed that I used two different compilers for building libtorrent and the libtorrent python bindings?

**Comment by zonca** [comment]
You filed this ticket on the wrong repository
