### ISSUE TITLE
ERROR using pixel weights with multiprocessing

### ISSUE THREAD

**Issue by pferreiraov** [healpy/healpy#569]
Hi, when I use the pixel_weigths option on map2alm or anafast (use_pixel_weights=True) with multiprocessing (multiple maps with different threads at the same time), I get the error message:

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "<ipython-input-2-f0a2363e0616>", line 1124, in map2alm_slices
    cl , result = hp.anafast(binnedmaps[i],lmax=lmax,use_pixel_weights=True)
  File "/home/pedro/.local/lib/python3.7/site-packages/healpy/sphtfunc.py", line 123, in anafast
    use_pixel_weights=use_pixel_weights,
  File "/home/pedro/.local/lib/python3.7/site-packages/healpy/sphtfunc.py", line 216, in map2alm
    package="healpy",
  File "/usr/lib/python3/dist-packages/astropy/utils/data.py", line 588, in get_pkg_data_filename
    timeout=remote_timeout)
  File "/usr/lib/python3/dist-packages/astropy/utils/data.py", line 1012, in download_file
    with shelve.open(urlmapfn) as url2hash:
  File "/usr/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.7/dbm/__init__.py", line 94, in open
    return mod.open(file, flag, mode)
_gdbm.error: [Errno 11] Resource temporarily unavailable
"""

The above exception was the direct cause of the following exception:

error                                     Traceback (most recent call last)
<ipython-input-4-dd8c1de13d53> in <module>()
----> 1 almrecover = dipole_doppler_low_res(alm,almfile=False,lmax=2048,overbin=10,threads=int(8),processes=int(2))

<ipython-input-2-f0a2363e0616> in dipole_doppler_low_res(alm, almfile, lmax, overbin, threads, processes)
   1127         return result
   1128     pool = mp.Pool(processes=processes)
-> 1129     binnedboostedalm = pool.map(map2alm_slices, range(nslices))
   1130     pool.terminate()
   1131     pool.join()

/usr/lib/python3.7/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

/usr/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

error: [Errno 11] Resource temporarily unavailable
```

How can I solve the error "Resource temporarily unavailable" ? This have any relation with the download of the weights data?

**Comment by pferreiraov** [comment]
@zonca ?

**Comment by zonca** [comment]
No need to tag me.
Please provide minimal example to reproduce this.

**Comment by zonca** [comment]
got no more feedback
