### ISSUE TITLE
Error compiling from current master branch on macOS 10.14.6.

### ISSUE THREAD

**Issue by demitri** [healpy/healpy#599]
Hi,

I just pulled the current version of healpy and am getting this error when trying to build:

```
% python setup.py build
running build
running build_py
running build_clib
checking if configure script for library 'cfitsio' exists
running 'autoreconf -i' for library 'cfitsio'
autoreconf: 'configure.ac' or 'configure.in' is required
Traceback (most recent call last):
  File "setup.py", line 547, in <module>
    scripts=['bin/healpy_get_wmap_maps.sh'],
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/anaconda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/anaconda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/local/anaconda/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 230, in finalize_options
    ["autoreconf", "-i"], cwd=build_info["local_source"], env=env
  File "/usr/local/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['autoreconf', '-i']' returned non-zero exit status 1.
```

The latest released version is working for me though.

**Comment by zonca** [comment]
sorry for the late reply.
For later reference, it seems that `configure.in` is missing, so it is possible that you hadn't checked out the submodules with `git submodule init`, `git submodule update`.

**Comment by demitri** [comment]
Thanks for the reply. This did not work for me. After doing a `git pull`:

```
 % git submodule init
Submodule 'cfitsio' (https://github.com/healpy/cfitsio.git) registered for path 'cfitsio'
Submodule 'healpixsubmodule' (https://github.com/healpy/healpixmirror.git) registered for path 'healpixsubmodule'
% git submodule update
Cloning into '/Users/demitri/Documents/Repositories/GitHub/healpy/cfitsio'...
Cloning into '/Users/demitri/Documents/Repositories/GitHub/healpy/healpixsubmodule'...
Submodule path 'cfitsio': checked out '6a1ea4ec55f0f4906b6e5723236b05cb1b0cfdac'
Submodule path 'healpixsubmodule': checked out '29d2a54dde968a4e71bdb06c193f607f0b98168a'
% python setup.py build
running build
running build_py
running build_clib
checking if configure script for library 'cfitsio' exists
checking if configure script for library 'sharp' exists
checking if configure script for library 'healpix_cxx' exists
running 'autoreconf -i' for library 'healpix_cxx'
configure.ac:119: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/autoconf-2.69/bin/autoconf failed with exit status: 1
Traceback (most recent call last):
  File "setup.py", line 476, in <module>
    scripts=["bin/healpy_get_wmap_maps.sh"],
  File "/usr/local/anaconda/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/anaconda/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/anaconda/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/anaconda/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/anaconda/lib/python3.7/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/local/anaconda/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 153, in finalize_options
    ["autoreconf", "-i"], cwd=build_info["local_source"], env=env
  File "/usr/local/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['autoreconf', '-i']' returned non-zero exit status 1.
% autoreconf -i
autoreconf: 'configure.ac' or 'configure.in' is required
```

I am on macOS 10.14.6, using Anaconda Python 3.7.7.

**Comment by zonca** [comment]
install libtool https://healpy.readthedocs.io/en/latest/install.html#development-install

**Comment by demitri** [comment]
I have libtool installed.

**Comment by zonca** [comment]
ok, sorry I have no access to a Mac OS machine to debug this.

**Comment by mreineck** [comment]
Just stabbing in the dark here: is it possible that there is more than one package on MacOS called `libtool` or similar, doing quite different things? You would need GNU libtool.

It's also possible that the `libtool` shipped with your OS is outdated. See this (really old) thread, which might help here: https://lists.gnu.org/archive/html/octave-maintainers/2009-12/msg00199.html

Sorry, I don't have access to Mac OS either, so I can only offer wild guesses.

**Comment by lpsinger** [comment]
Are you sure you have automake as well? Building from git requires the autotools trifecta: autoconf, automake, and libtool.

**Comment by ntessore** [comment]
I just ran into this on macOS. It was a missing libtool first, then automake, as you guys said.
