### ISSUE TITLE
Installing healpy on Ubuntu 18.04 system

### ISSUE THREAD

**Issue by houriziaeepour** [healpy/healpy#601]
I am trying to install healpy in Healpix_3.60 on Ubuntu 18.04, but I receive compilation errors. I have tried with both HPY_PYTHON = python and HPY_PYTHON = python3. Neither of cases works. Can you please help? Here is the result for compilation with python3:
> make healpy-all
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    pkg_resources.require("setuptools >= 3.2")
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools>=3.2' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from ez_setup import use_setuptools
  File "/home/hziaeep/src/Healpix_3.60/src/healpy/ez_setup.py", line 21, in <module>
    from distutils import log
ImportError: cannot import name 'log'
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    pkg_resources.require("setuptools >= 3.2")
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools>=3.2' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from ez_setup import use_setuptools
  File "/home/hziaeep/src/Healpix_3.60/src/healpy/ez_setup.py", line 21, in <module>
    from distutils import log
ImportError: cannot import name 'log'

**Comment by zonca** [comment]
Have you tried installing setuptools?
Also why compile from source what about installing with conda or pip?

**Comment by houriziaeepour** [comment]
Hi Andrea

Thank you for the quick reply. I am not a python user. I just wanted to
compile healpy to have a complete installation of Healpix software on my
laptop. I will follow your suggestion.

Cheers
Houri

**Comment by lpsinger** [comment]
Hi @houriziaeepour, even easier would be to install it using your package manager:

`sudo apt-get install python3-healpy`

**Comment by houriziaeepour** [comment]
Thanks for the hint
Cheers
Houri
