### ISSUE TITLE
Passing parameters norm and vmin/vmax simultaneously is not supported. 

### ISSUE THREAD

**Issue by gshennessy** [healpy/healpy#750]
Using healpy 1.14 and matplotlib 3.5 from astroconda a call to healpy.mollview
throws an error message of:

Traceback (most recent call last):
  File "plot_sky.py", line 39, in <module>
    main()
  File "plot_sky.py", line 31, in main
    H.mollview(map)
  File "/home/gregory.hennessy/.conda/envs/astroconda/lib/python3.7/site-packages/healpy/visufunc.py", line 260, in mollview
    norm=norm,
  File "/home/gregory.hennessy/.conda/envs/astroconda/lib/python3.7/site-packages/healpy/projaxes.py", line 736, in projmap
    return super(HpxMollweideAxes, self).projmap(map, f, **kwds)
  File "/home/gregory.hennessy/.conda/envs/astroconda/lib/python3.7/site-packages/healpy/projaxes.py", line 726, in projmap
    img = super(MollweideAxes, self).projmap(map, vec2pix_func, **kwds)
  File "/home/gregory.hennessy/.conda/envs/astroconda/lib/python3.7/site-packages/healpy/projaxes.py", line 211, in projmap
    **kwds
  File "/home/gregory.hennessy/.conda/envs/astroconda/lib/python3.7/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/home/gregory.hennessy/.conda/envs/astroconda/lib/python3.7/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/gregory.hennessy/.conda/envs/astroconda/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5447, in imshow
    im._scale_norm(norm, vmin, vmax)
  File "/home/gregory.hennessy/.conda/envs/astroconda/lib/python3.7/site-packages/matplotlib/cm.py", line 381, in _scale_norm
    "Passing parameters norm and vmin/vmax simultaneously is "
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

**Comment by zonca** [comment]
thanks, please also show the call. what version of matplotlib?
would you be able to fix this and make a pull request?

**Comment by gshennessy** [comment]
```
#! /usr/bin/env python

import healpy as H
import pylab as PL
import numpy as NP

def main():
    nest=6
    nside=2**nest
    map = NP.zeros(H.nside2npix(nside))
    for i in range(1000):
        map[i] = i % 5

    H.mollview(map)
    PL.show()
    return


if __name__ == "__main__":
    main()
```

the version of matplotlib is 2.5.0

error stack is:

(astropy) [ariel:3 bc3]$ python show_errors.py
Traceback (most recent call last):
  File "/share/gregory.hennessy/bc3/show_errors.py", line 21, in <module>
    main()
  File "/share/gregory.hennessy/bc3/show_errors.py", line 15, in main
    H.mollview(map)
  File "/home/gregory.hennessy/.conda/envs/astropy/lib/python3.9/site-packages/healpy/visufunc.py", line 250, in mollview
    img = ax.projmap(
  File "/home/gregory.hennessy/.conda/envs/astropy/lib/python3.9/site-packages/healpy/projaxes.py", line 736, in projmap
    return super(HpxMollweideAxes, self).projmap(map, f, **kwds)
  File "/home/gregory.hennessy/.conda/envs/astropy/lib/python3.9/site-packages/healpy/projaxes.py", line 726, in projmap
    img = super(MollweideAxes, self).projmap(map, vec2pix_func, **kwds)
  File "/home/gregory.hennessy/.conda/envs/astropy/lib/python3.9/site-packages/healpy/projaxes.py", line 202, in projmap
    aximg = self.imshow(
  File "/home/gregory.hennessy/.conda/envs/astropy/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/home/gregory.hennessy/.conda/envs/astropy/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/gregory.hennessy/.conda/envs/astropy/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5447, in imshow
    im._scale_norm(norm, vmin, vmax)
  File "/home/gregory.hennessy/.conda/envs/astropy/lib/python3.9/site-packages/matplotlib/cm.py", line 380, in _scale_norm
    raise ValueError(
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.

**Comment by gshennessy** [comment]
> 

I'm willing to do what I can to assist in the process, but I'm not an expert. what sort of things should
be done to figure out which version is the latest that things still work?

**Comment by zonca** [comment]
I think you should try to use  projview

**Comment by zonca** [comment]
I think you should try to use  projview

**Comment by zonca** [comment]
I tried healpy 1.15 with matplotlib 3.5.1 and your example works fine,
please upgrade healpy to 1.15, that might fix the problem
