### ISSUE TITLE
healpy.mollview() will error even with no arguments passed

### ISSUE THREAD

**Issue by pmberg** [healpy/healpy#768]
When I run healpy.mollview() with no arguments passed, I would expect it to use the default values and create a blank mollview. However, instead it returns:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/submit/pmberg/miniconda3/envs/py3/lib/python3.7/site-packages/healpy/visufunc.py", line 260, in mollview
    norm=norm,
  File "/home/submit/pmberg/miniconda3/envs/py3/lib/python3.7/site-packages/healpy/projaxes.py", line 736, in projmap
    return super(HpxMollweideAxes, self).projmap(map, f, **kwds)
  File "/home/submit/pmberg/miniconda3/envs/py3/lib/python3.7/site-packages/healpy/projaxes.py", line 726, in projmap
    img = super(MollweideAxes, self).projmap(map, vec2pix_func, **kwds)
  File "/home/submit/pmberg/miniconda3/envs/py3/lib/python3.7/site-packages/healpy/projaxes.py", line 211, in projmap
    **kwds
  File "/home/submit/pmberg/miniconda3/envs/py3/lib/python3.7/site-packages/matplotlib/_api/deprecation.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "/home/submit/pmberg/miniconda3/envs/py3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/submit/pmberg/miniconda3/envs/py3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 5493, in imshow
    im._scale_norm(norm, vmin, vmax)
  File "/home/submit/pmberg/miniconda3/envs/py3/lib/python3.7/site-packages/matplotlib/cm.py", line 381, in _scale_norm
    "Passing parameters norm and vmin/vmax simultaneously is "
ValueError: Passing parameters norm and vmin/vmax simultaneously is not supported. Please pass vmin/vmax directly to the norm when creating it.`

I can repeat the issue by typing:

`import healpy as hp
hp.mollview()`

Could the healpy contributors please fix this as soon as possible?

**Comment by hongwanliu** [comment]
I am encountering exactly the same error as well.

**Comment by zonca** [comment]
It seems a corner case to me, so I don't feel investing time fixing it.
But I would gladly review a pull request.

**Comment by Grogroda** [comment]
I'm getting almost the same error message when I use mollview with the simple example in the [tutorial](https://healpy.readthedocs.io/en/latest/tutorial.html), though I use anaconda and not miniconda. Full explanation [here](https://stackoverflow.com/questions/73887503/healpy-mollview-valueerror-for-colormap?noredirect=1#comment130484545_73887503).
