### ISSUE TITLE
build_ext fails since some time

### ISSUE THREAD

**Issue by olebole** [healpy/healpy#800]
Since some days, the Debian package fails to build with the message
```
running build_ext
Traceback (most recent call last):
  File "/build/healpy-1.16.1/setup.py", line 323, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/build/healpy-1.16.1/setup.py", line 312, in run
    build_ext.run(self)
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/lib/python3/dist-packages/Cython/Distutils/old_build_ext.py", line 190, in build_extensions
    self.check_extensions_list(self.extensions)
  File "/usr/lib/python3.10/distutils/command/build_ext.py", line 362, in check_extensions_list
    raise DistutilsSetupError(
distutils.errors.DistutilsSetupError: each element of 'ext_modules' option must be an Extension instance or 2-tuple
```
which I do not fully understand.  This is also reported as [Debian#1022486](https://bugs.debian.org/1022486).

### Versions:

* healpy 1.14.1 (original bug report), still found in 1.16.1
* setuptools 65.5.0
* distutils 3.10.8
* Python 3.10.3
* cython 0.29.32

A full build log for Healpy 1.16.1 is attached: [healpy_1.16.1-1.txt](https://github.com/healpy/healpy/files/9910852/healpy_1.16.1-1.txt)

**Comment by lpsinger** [comment]
@olebole, I'm working on updating all of the HEALPix Debian packages today. I'll need your help uploading them, though, as I cannot get quickly to my Debian key.

**Comment by olebole** [comment]
@lpsinger I already made a team upload to Debian with an updated healpy and the re-ordered imports as a workaround.
