### ISSUE TITLE
Build wheels for macOS arm64

### ISSUE THREAD

**Issue by orifox** [healpy/healpy#835]
Hi,

I followed the instructions here: https://healpy.readthedocs.io/en/latest/install.html#source-installation-with-pip-not-usually-recommended

But still getting the error below:

` a - f77_wrap2.o
      a - f77_wrap3.o
      a - f77_wrap4.o
      /bin/cp -a libcfitsio.a /private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-install-nnrd5y8f/healpy_5fd1ed5df3514ac083fca6856486b7c9/build/temp.macosx-11.0-arm64-cpython-310/lib
      /bin/cp fitsio.h fitsio2.h longnam.h drvrsmem.h /private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-install-nnrd5y8f/healpy_5fd1ed5df3514ac083fca6856486b7c9/build/temp.macosx-11.0-arm64-cpython-310/include
      /bin/cp cfitsio.pc /private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-install-nnrd5y8f/healpy_5fd1ed5df3514ac083fca6856486b7c9/build/temp.macosx-11.0-arm64-cpython-310/lib/pkgconfig
      /private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-install-nnrd5y8f/healpy_5fd1ed5df3514ac083fca6856486b7c9/run_pykg_config.py:6: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated. Requirements should be satisfied by a PEP 517 installer. If you are using pip, you can try `pip install --use-pep517`.
        Distribution().fetch_build_eggs(requirement)
      /Users/ofox/miniconda3/envs/lrsoptimal2/bin/python3.10: No module named pip
      Traceback (most recent call last):
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/installer.py", line 97, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/Users/ofox/miniconda3/envs/lrsoptimal2/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/ofox/miniconda3/envs/lrsoptimal2/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/tmpqptr2hde', '--quiet', 'pykg-config>=1.2.0']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-install-nnrd5y8f/healpy_5fd1ed5df3514ac083fca6856486b7c9/run_pykg_config.py", line 6, in <module>
          Distribution().fetch_build_eggs(requirement)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 894, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/installer.py", line 99, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/ofox/miniconda3/envs/lrsoptimal2/bin/python3.10', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/tmpqptr2hde', '--quiet', 'pykg-config>=1.2.0']' returned non-zero exit status 1.
      Traceback (most recent call last):
        File "<string>", line 143, in build_library
        File "<string>", line 108, in pkgconfig
        File "/Users/ofox/miniconda3/envs/lrsoptimal2/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/ofox/miniconda3/envs/lrsoptimal2/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '('/Users/ofox/miniconda3/envs/lrsoptimal2/bin/python3.10', '/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-install-nnrd5y8f/healpy_5fd1ed5df3514ac083fca6856486b7c9/run_pykg_config.py', '--cflags-only-I', 'cfitsio')' returned non-zero exit status 1.
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/ofox/miniconda3/envs/lrsoptimal2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/ofox/miniconda3/envs/lrsoptimal2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ofox/miniconda3/envs/lrsoptimal2/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 323, in <module>
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-build-env-874d0jgu/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_clib.py", line 111, in run
          self.build_libraries(self.libraries)
        File "<string>", line 273, in build_libraries
        File "<string>", line 206, in build_library
        File "<string>", line 108, in pkgconfig
        File "/Users/ofox/miniconda3/envs/lrsoptimal2/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/ofox/miniconda3/envs/lrsoptimal2/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '('/Users/ofox/miniconda3/envs/lrsoptimal2/bin/python3.10', '/private/var/folders/yh/kl4y3s1x3_j3ywy3qq67g3vc0001kc/T/pip-install-nnrd5y8f/healpy_5fd1ed5df3514ac083fca6856486b7c9/run_pykg_config.py', '--cflags-only-I', 'cfitsio')' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for healpy
Failed to build healpy
ERROR: Could not build wheels for healpy, which is required to install pyproject.toml-based projects`

**Comment by lpsinger** [comment]
Thanks, @orifox. There is a long-standing issue that we do not yet have wheels for macOS arm64. We are relying on GitHub Actions hosted runners to build our wheels, and GitHub still doesn’t have any Apple Silicon runners.

Do you use Anaconda? As a workaround, there is a Conda package for healpy that you can use on an Apple Silicon Mac.
