### ISSUE TITLE
ImportError with python 3.13

### ISSUE THREAD

**Issue by cbischoff** [healpy/healpy#972]
Installing healpy with pip on an Intel i5 MacBook Air. Both python@3.12 and python@3.13 were installed with homebrew.

This works (no ImportError):
```
$ python3.12 -m venv .venv/hp12
$ source .venv/hp12/bin/activate
$ pip install healpy
...
Successfully installed PyYAML-6.0.2 astropy-6.1.4 astropy-iers-data-0.2024.10.7.0.32.46 healpy-1.17.3 numpy-2.1.2 packaging-24.1 pyerfa-2.0.1.4
$ python
>>> import healpy
```

But then I try the following:
```
$ python3.13 -m venv .venv/hp13
$ source .venv/hp13/bin/activate
$ pip install healpy
...
Successfully installed PyYAML-6.0.2 astropy-6.1.4 astropy-iers-data-0.2024.10.7.0.32.46 healpy-1.17.3 numpy-2.1.2 packaging-24.1 pyerfa-2.0.1.4
$ python
>>> import healpy
Warning: cannot import _healpy_pixel_lib module
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import healpy as hp
  File "/Users/colin/.venv/hp13/lib/python3.13/site-packages/healpy/__init__.py", line 65, in <module>
    from .sphtfunc import (
    ...<21 lines>...
    )
  File "/Users/colin/.venv/hp13/lib/python3.13/site-packages/healpy/sphtfunc.py", line 32, in <module>
    from . import _healpy_sph_transform_lib as sphtlib
ImportError: dlopen(/Users/colin/.venv/hp13/lib/python3.13/site-packages/healpy/_healpy_sph_transform_lib.cpython-313-darwin.so, 0x0002): Library not loaded: /private/var/folders/h2/xq1mclc50b3b6h9f5v605xfm0000gn/T/pip-install-46e6gvw3/healpy_de4dc60e42e247f1824b45b8f7a62b13/build/temp.macosx-14.0-x86_64-cpython-313/lib/libsharp.2.dylib
  Referenced from: <2E2C5A48-FE85-3805-AA05-658D83BF9D58> /Users/colin/.venv/hp13/lib/python3.13/site-packages/healpy/_healpy_sph_transform_lib.cpython-313-darwin.so
  Reason: tried: '/private/var/folders/h2/xq1mclc50b3b6h9f5v605xfm0000gn/T/pip-install-46e6gvw3/healpy_de4dc60e42e247f1824b45b8f7a62b13/build/temp.macosx-14.0-x86_64-cpython-313/lib/libsharp.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/h2/xq1mclc50b3b6h9f5v605xfm0000gn/T/pip-install-46e6gvw3/healpy_de4dc60e42e247f1824b45b8f7a62b13/build/temp.macosx-14.0-x86_64-cpython-313/lib/libsharp.2.dylib' (no such file), '/private/var/folders/h2/xq1mclc50b3b6h9f5v605xfm0000gn/T/pip-install-46e6gvw3/healpy_de4dc60e42e247f1824b45b8f7a62b13/build/temp.macosx-14.0-x86_64-cpython-313/lib/libsharp.2.dylib' (no such file), '/usr/local/lib/libsharp.2.dylib' (no such file), '/usr/lib/libsharp.2.dylib' (no such file, not in dyld cache)
```

**Comment by zonca** [comment]
See https://github.com/healpy/healpy/issues/971
